### PR TITLE
Subscribe stanza for PubSub (XEP-0060)

### PR DESCRIPTION
**Pull request by wende**

### CODE REVIEW

**Comment by scrogson** [comment]
Can you please squash this into one commit and then add a `@doc` and possibly an example that would be used by `doctest`?

This will be a great addition.

**Comment by iraasta** [comment]
Yeah. I wanted to, but I've had issues with emacs making tabs instead of
spaces. I'll add that tomorrow morning

**Comment by iraasta** [comment]
Unfortunately I can't make doctest because it takes ID which has side effects

**Comment by scrogson** [comment]
@iraasta ok, don't worry about the doctest. Here's an example of how you can write a test that will work with the generated `id`: https://github.com/scrogson/hedwig/blob/master/test/hedwig/stanza_test.exs#L41

**Comment by scrogson** [comment]
Thank you for the contribution. I'll go ahead and write a test for it.

**Comment by wende** [comment]
Oh. Yeah, sorry about that. totally forgot
Thank You

2015-09-08 21:19 GMT+02:00 Sonny Scroggin <notifications@github.com>:

> Thank you for the contribution. I'll go ahead and write a test for it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scrogson/hedwig/pull/12#issuecomment-138674898>.
>



-- 
Krzysztof Wende
Neon Tree Solutions Ltd.
http://neontree.pl

**Pull request merged**
